### ISSUE TITLE
[500] As a visitor I can access to different seasons from the season page 

### ISSUE THREAD

**Issue by delenneg** [WildCodeSchool/lyon-php-2003-project2-databuzz#63]
- [ ] Links are displaying other seasons

**Comment by martinotm** [comment]
Pourquoi on retrouve cette US dans le Sprint backlog alors qu il y en a d autres plus prioritaires ?

**Comment by delenneg** [comment]
On l'a repriorisée en faisant le point sur nos priorités en le mettant dans notre sprint mais on a oublié de modifier sa priorité... c'est prioritaire car sinon on est obligé de revenir sur la page tvshow pour consulter une autre saison, ce qui n'a pas trop de sens selon nous. Je modifie sa priorité du coup.
